### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by sanieni6** [sanieni6/artworkListing-app#21]
# Group capstone: set up your Kanban board
In this activity, My team will prepare a Kanban board with a GitHub project:
https://github.com/sanieni6/artworkListing-app/projects/1
My team is made up of @sanieni6  and @fmanimashaun

**Comment by binhussen** [comment]
Hi @sanieni6 and @fmanimashaun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Prepred Kanban board ✔️
- Listed their group members ✔️
- Added link to their GitHub project ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
